[versions]

ble = "2.10.1"
compileSdk = "34"

androidGradlePlugin = "8.7.3"
androidMaterial = "1.12.0"
androidxActivity = "1.9.1"
androidxAppcompat = "1.7.0"
androidxComposeBom = "2024.06.00"
androidxCoreKtx = "1.13.1"
androidxHiltNavigationCompose = "1.2.0"
androidxLifecycle = "2.8.4"
androidxNavigation = "2.8.0-beta06"
androidxTestEspresso = "3.5.1"
androidxTestExt = "1.1.5"
androidxTestRules = "1.6.1"
androidxTestRunner = "1.6.1"
lottie = "6.4.1"
cloudHttpWebsocket = "1.3.9"
constraintlayout = "2.1.4"
gson = "2.9.1"
guava = "33.2.0-android"
usbSerialForAndroid = "3.8.1"
zxing = "3.5.0"
okio = "3.2.0"
perfmark = "0.26.0"
rxjava = "3.1.8"
rxandroid = "3.0.0"
apache = "3.7"

agp = "8.7.3"
androidTools = "31.5.0"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.21"
room = "2.6.1"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.04.01"
jetbrainsKotlinJvm = "2.0.0"
androidDesugarJdkLibs = "2.0.4"
daggerHiltAndroid = "2.51.1"
dagger = "2.56.2"
appcompat = "1.7.0"
material = "1.12.0"
runtimeLivedata = "1.7.6"
uiToolingPreviewAndroid = "1.7.7"
okhttp = "4.11.0"
camerax = "1.4.2"
koin = "3.5.0"
foundationAndroid = "1.6.1"
databindingCommon = "8.10.0"
runtimeLivedataVersion = "1.8.3"
translate = "17.0.3"
foundationLayout = "1.9.5"
uiText = "1.9.5"

[libraries]
ble = { module = "no.nordicsemi.android:ble", version.ref = "ble" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
camerax-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camerax-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camerax-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-animation-core = { group = "androidx.compose.animation", name = "animation-core" }
androidx-compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material-ripple = { group = "androidx.compose.material", name = "material-ripple" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowsizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-runtime-rxjava2 = { group = "androidx.compose.runtime", name = "runtime-rxjava2" }
androidx-compose-runtime-rxjava3 = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.9.0" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.6.0" }

lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "androidxNavigation" }
androidx-navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "androidxNavigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "androidxNavigation" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHiltAndroid" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-extension = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
com-google-code-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
com-google-guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
com-google-zxing-javase = { group = "com.google.zxing", name = "javase", version.ref = "zxing" }
com-google-zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
com-squareup-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
io-perfmark = { group = "io.perfmark", name = "perfmark-api", version.ref = "perfmark" }
io-reactivex-rxjava3-rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
io-reactivex-rxjava3-rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
org-apache-commons = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apache" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
androidx-databinding-common = { group = "androidx.databinding", name = "databinding-common", version.ref = "databindingCommon" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedataVersion" }
usb-serial-for1-android = { module = "com.github.mik3y:usb-serial-for-android", version.ref = "usbSerialForAndroid" }
translate = { group = "com.google.mlkit", name = "translate", version.ref = "translate" }
androidx-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }

[bundles]
camerax = ["camerax-core", "camerax-camera2", "camerax-lifecycle", "camerax-view"]

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHiltAndroid" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
generic-application = { id = "generic.application", version = "unspecified" }
generic-application-compose = { id = "generic.application.compose", version = "unspecified" }
generic-feature = { id = "generic.feature", version = "unspecified" }
generic-hilt = { id = "generic.hilt", version = "unspecified" }
generic-dagger = { id = "generic.dagger", version = "unspecified" }
generic-library = { id = "generic.library", version = "unspecified" }
generic-library-compose = { id = "generic.library.compose", version = "unspecified" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
generic-android-room = { id = "generic.android.room", version = "unspecified" }
koi-android-application-flavors = { id = "koi.android.application.flavors" }
koi-android-library-flavors = { id = "koi.android.library.flavors" }
koi-android-datamodel-flavors = { id = "koi.android.datamodel.flavors" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize" }
